---
- hosts: all
  become: true
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  tasks:
  - name: install python3 packages
    apt: "pkg={{ item }} state=latest"
    with_items:
      - python3
      - python3-venv
      - python3-dev
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-pip
      - postgresql
      - postgresql-contrib
    environment:
      LC_ALL: C
  - name: install pip packages
    pip:
      name: "-r /vagrant/requirements.txt"
      executable: /usr/bin/pip3
    environment:
      LC_ALL: C