# Generated by Django 2.0.5 on 2018-05-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='email_sent'),
        ),
    ]
