# Generated by Django 2.0.3 on 2018-05-06 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth_poc', '0002_auto_20180415_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauth2token',
            name='id',
        ),
        migrations.AddField(
            model_name='oauth2token',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
